apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#metadata:
#  name: arbitrary

commonLabels:
  app: demoforprofile      # 所有的resource都會被打上這個label

resources: # 設定有哪些yaml檔案
  - deployment.yaml
  - service.yaml