apiVersion: v1
kind: Service
metadata:
  name: demoforprofile-service
  namespace: demoforprofile
spec:
  selector:
    app: demoforprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
